[package]
name = "dfs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.11.6"
log = "0.4.26"
rusqlite = "0.35.0"

[build]
target-dir = "bin/"

[profile.dev]
opt-level = 1
